// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1EVwE4R9LLmSV5n3JCNRpSNMjDnzT5gw',
    appId: '1:155652134190:web:66931d96299d09ae6b96bf',
    messagingSenderId: '155652134190',
    projectId: 'novo-flashmart',
    authDomain: 'novo-flashmart.firebaseapp.com',
    storageBucket: 'novo-flashmart.appspot.com',
    measurementId: 'G-R767W7WVQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFHjdDOOZSYN6fCvOyoh3RCE_pNW9hHQo',
    appId: '1:155652134190:android:2ef7b2f3978290986b96bf',
    messagingSenderId: '155652134190',
    projectId: 'novo-flashmart',
    storageBucket: 'novo-flashmart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC36hBzoQ1Av6rI1fm6qIqvLdEih5dbvrw',
    appId: '1:155652134190:ios:7b93a47faac5b0d16b96bf',
    messagingSenderId: '155652134190',
    projectId: 'novo-flashmart',
    storageBucket: 'novo-flashmart.appspot.com',
    iosBundleId: 'com.novo.novoFlashMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC36hBzoQ1Av6rI1fm6qIqvLdEih5dbvrw',
    appId: '1:155652134190:ios:c2d42c0707f98ed46b96bf',
    messagingSenderId: '155652134190',
    projectId: 'novo-flashmart',
    storageBucket: 'novo-flashmart.appspot.com',
    iosBundleId: 'com.novo.mart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1EVwE4R9LLmSV5n3JCNRpSNMjDnzT5gw',
    appId: '1:155652134190:web:a817cd99f1f95a846b96bf',
    messagingSenderId: '155652134190',
    projectId: 'novo-flashmart',
    authDomain: 'novo-flashmart.firebaseapp.com',
    storageBucket: 'novo-flashmart.appspot.com',
    measurementId: 'G-B5L8S8D6BL',
  );

}